<a href="https://colab.research.google.com/github/johanasev/Introducci-n-a-la-IA/blob/main/content/LAB%2001.01%20-%20PRACTICE%20SUBMISSION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LAB 01.01 - Practice submission

In [14]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/ai4eng.v1/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()


In [15]:
import inspect
from local.lib.rlxmoocapi import session
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L01.01", varname="student");

logging in as johana.sevillano@udea.edu.co... please wait
using course session ai4eng.v1.udea.r3::2024.1
success!! you are logged in


### Ejercicio 1: Suma dos matrices

Completa la función `suma_matrices` para que, dadas dos arrays numpy cualquiera devuelva la suma elemento a elemento.

#### Ejemplo de ejecución

    > s = np.array([1,2,3])
    > t = np.array([4,5,6])
    > suma_matrices(s,t)
    
      [5 7 9]
     
_Sugerencia_: completa el código de la siguiente manera:

    def suma_matrices(a,b):
       ## --- TU CODIGO AQUI ---
       result = a + b
       return result

In [8]:
import numpy as np
def suma_matrices(a,b):
    ## --- TU CODIGO AQUI ---
    result = a + b
    return result
    print(suma_matrices(a, b))


comprueba manualmente tu código

In [5]:
import numpy as np
a = np.random.randint(10, size=(3,2))
b = np.random.randint(10, size=(3,2))
print (a)
print (b)
print (suma_matrices(a,b))

[[4 1]
 [1 7]
 [9 4]]
[[6 8]
 [8 7]
 [7 0]]
[[10  9]
 [ 9 14]
 [16  4]]


#### registra tu solución en línea

In [9]:
student.submit_task(globals(), task_id="task_01");

### Ejercicio 2: Realiza un cálculo

En este ejercicio, al ejecutar la celda de más abajo, se generará una lista de número aleatorios.

Tendrás que calcular el valor promedio de la lista y asignarlo a la variable `avg` más abajo.

Puedes usar el método que quieras para realizar el cálculo (a mano, excel, python, etc.) lo que importa es el valor que obtengas.


In [10]:
import numpy as np
rlist = np.random.randint(100, size=10)
rlist

array([34, 98, 17, 40, 26, 65, 55, 95, 94, 76])

#### tu solución

In [16]:
import numpy as np
array = np.array([34, 98, 17, 40, 26, 65, 55, 95, 94, 76])
avg = np.mean(array)
print("Promedio del array: ", avg)

Promedio del array:  60.0


#### registra tu solución en línea

In [17]:
student.submit_task(globals(), task_id="task_02");